### ISSUE TITLE
Issue insalling with pip on a macos venv

### ISSUE THREAD

**Issue by zseramnay** [alexanderlerch/pyACA#12]
I'm trying to install pyACA in a venv but I can't succed to install pyACA.

The erros is :
pip install https://github.com/alexanderlerch/pyACA.git
Collecting https://github.com/alexanderlerch/pyACA.git
  Downloading https://github.com/alexanderlerch/pyACA.git
     / 162 kB 2.4 MB/s
  ERROR: Cannot unpack file /private/var/folders/23/_3qwnfqc8xj09j006s6mmcgr0000gp/T/pip-unpack-7hnq4j91/pyACA.git (downloaded from /private/var/folders/23/_3qwnfqc8xj09j006s6mmcgr0000gp/T/pip-req-build-768hmqvn, content-type: text/html; charset=utf-8); cannot detect archive format
ERROR: Cannot determine archive format of /private/var/folders/23/_3qwnfqc8xj09j006s6mmcgr0000gp/T/pip-req-build-768hmqvn

All the best
Yan

**Comment by alexanderlerch** [comment]
Not an expert, but shouldn't the command line look like
`pip install git+https://github.com/alexanderlerch/pyACA.git`?

See, for example, the information available [here](https://adamj.eu/tech/2019/03/11/pip-install-from-a-git-repository/)

**Comment by zseramnay** [comment]
Thank you so much...
All set now.
newbie here.

Cheers
Yan
