### ISSUE TITLE
A little oversight in sample code

### ISSUE THREAD

**Issue by paranoid2droid** [alexanderlerch/pyACA#4]
Hi Professor Alexander,

There is a little oversight in the code that may be confusing when running the sample code, not a problem though.

In the function `computeFeatureCl` [https://github.com/alexa nderlerch/pyACA/blob/cd1bcad2f0fee38037ef4e9b9929e03a95ae8491/pyACA/computeFeature.py#L111](url) 

```
def computeFeatureCl(cPath, cFeatureName, bPlotOutput = False):

    # read audio file
    [f_s, afAudioData] = ToolReadAudio(cPath)
    afAudioData = np.sin(2*np.pi * np.arange(f_s*1)*440./f_s)
```

The test code was not commented so 'afAudioData' is always overwritten after reading from a wav file.

Thanks for your work!

Sincerely,
Zhe

**Comment by alexanderlerch** [comment]
Oops.
